baseurl             = "https://vilisimo.github.io/"
contentdir          = "content"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "emperor"
author              = "Simonas Viliunas"
title               = "Machine Code Never Lies"
builddrafts         = false
canonifyurls        = true
googleAnalytics     = "UA-123-45"
pluralizelisttitles = false
languageCode        = "en-us"

[blackfriday]
hrefTargetBlank     = true

[permalinks]
blog                   = "blog/:slug/"

[[menu.main]]
name                   = "Home"
weight                 = -130
identifier             = "home"
url                    = "/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "Projects"
weight                 = -110
identifier             = "projects"
url                    = "/projects/"

[[menu.main]]
name                   = "About"
weight                 = -100
identifier             = "about"
url                    = "/about/"

[params]